In [2]:
from IPython.display import HTML

# standard imports
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt
import math
from math import pi
np.set_printoptions(
    linewidth=120, formatter={
        'float': lambda x: f"{0:8.4g}" if abs(x) < 1e-10 else f"{x:8.4g}"})
np.random.seed(0)
from spatialmath import *
from spatialmath.base import *

### Transforming Spatial Velocities

In [3]:
aTb = SE3.Tx(-2) * SE3.Rz(-pi/2) * SE3.Rx(pi/2)
aTb

   0         0        -1        -2         
  -1         0         0         0         
   0         1         0         0         
   0         0         0         1         


In [4]:
bV = [1, 2, 3, 4, 5, 6]

In [5]:
aJb = aTb.jacob()
aJb.shape

(6, 6)

In [6]:
aJb

array([[       0,        0,       -1,        0,        0,        0],
       [      -1,        0,        0,        0,        0,        0],
       [       0,        1,        0,        0,        0,        0],
       [       0,        0,        0,        0,        0,       -1],
       [       0,        0,        0,       -1,        0,        0],
       [       0,        0,        0,        0,        1,        0]])

In [7]:
aV = aJb @ bV
aV

array([      -3,       -1,        2,       -6,       -4,        5])

In [8]:
aV = aTb.Ad() @ [1, 2, 3, 0, 0, 0]
aV

array([      -3,       -1,        2,        0,        0,        0])

In [9]:
aV = aTb.Ad() @ [0, 0, 0, 1, 0, 0]
aV

array([       0,        0,        2,        0,       -1,        0])

In [10]:
aV = aTb.Ad() @ [1, 2, 3, 1, 0, 0]
aV

array([      -3,       -1,        4,        0,       -1,        0])

### Incremental Rotation